set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_SYSROOT $ENV{HOME}/cross/native/)
set(CMAKE_FIND_ROOT_PATH $ENV{HOME}/cross/native/)

set(CMAKE_STAGING_PREFIX /home/devel/stage)

set(CMAKE_C_COMPILER gcc)
set(CMAKE_CXX_COMPILER g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# set(PRELOAD_S6 ON)
